Silver Layer Processing - Grocery Inventory Dataset

Notebook ini digunakan untuk proses Data Engineering pada Silver Layer:
- Data Cleaning
- Data Transformation
- Feature Engineering
- Data Validation
- Export ke Silver Layer

In [2]:
import pandas as pd

1. Load Data (Bronze Layer)

In [ ]:

df = pd.read_csv('Grocery_Inventory new v1.csv')
df.head()

,Product_Name,Catagory,Supplier_Name,Warehouse_Location,Status,Product_ID,Supplier_ID,Date_Received,Last_Order_Date,Expiration_Date,Stock_Quantity,Reorder_Level,Reorder_Quantity,Unit_Price,Sales_Volume,Inventory_Turnover_Rate,percentage
0,Bell Pepper,Fruits & Vegetables,Eimbee,20 Pennsylvania Parkway,Discontinued,29-017-6255,43-348-2450,3/1/2024,1/6/2025,1/31/2025,46,64,17,$4.60,96,55,1.96%
1,Vegetable Oil,Oils & Fats,Digitube,03643 Oakridge Lane,Backordered,79-569-8856,04-854-7165,4/1/2024,5/19/2024,6/11/2024,51,87,86,$2.00,24,83,0.91%
2,Parmesan Cheese,Dairy,BlogXS,73 Graedel Street,Discontinued,28-146-2641,82-995-0739,4/1/2024,12/21/2024,4/8/2024,38,67,66,$12.00,35,24,1.36%
3,Carrot,Fruits & Vegetables,Avaveo,44801 Myrtle Center,Discontinued,11-581-9869,22-867-3079,5/1/2024,12/12/2024,9/26/2024,51,60,98,$1.50,44,95,1.36%
4,Garlic,Fruits & Vegetables,Katz,6195 Monterey Center,Discontinued,13-202-4809,24-281-7685,5/1/2024,7/28/2024,5/20/2024,27,22,89,$7.00,91,77,2.17%

2. Data Cleaning

In [ ]:
print(df.isnull().sum())

df = df.drop_duplicates()

df = df.dropna()

df.head()

Product_Name               0
Catagory                   1
Supplier_Name              0
Warehouse_Location         0
Status                     0
Product_ID                 0
Supplier_ID                0
Date_Received              0
Last_Order_Date            0
Expiration_Date            0
Stock_Quantity             0
Reorder_Level              0
Reorder_Quantity           0
Unit_Price                 0
Sales_Volume               0
Inventory_Turnover_Rate    0
percentage                 0
dtype: int64

,Product_Name,Catagory,Supplier_Name,Warehouse_Location,Status,Product_ID,Supplier_ID,Date_Received,Last_Order_Date,Expiration_Date,Stock_Quantity,Reorder_Level,Reorder_Quantity,Unit_Price,Sales_Volume,Inventory_Turnover_Rate,percentage
0,Bell Pepper,Fruits & Vegetables,Eimbee,20 Pennsylvania Parkway,Discontinued,29-017-6255,43-348-2450,3/1/2024,1/6/2025,1/31/2025,46,64,17,$4.60,96,55,1.96%
1,Vegetable Oil,Oils & Fats,Digitube,03643 Oakridge Lane,Backordered,79-569-8856,04-854-7165,4/1/2024,5/19/2024,6/11/2024,51,87,86,$2.00,24,83,0.91%
2,Parmesan Cheese,Dairy,BlogXS,73 Graedel Street,Discontinued,28-146-2641,82-995-0739,4/1/2024,12/21/2024,4/8/2024,38,67,66,$12.00,35,24,1.36%
3,Carrot,Fruits & Vegetables,Avaveo,44801 Myrtle Center,Discontinued,11-581-9869,22-867-3079,5/1/2024,12/12/2024,9/26/2024,51,60,98,$1.50,44,95,1.36%
4,Garlic,Fruits & Vegetables,Katz,6195 Monterey Center,Discontinued,13-202-4809,24-281-7685,5/1/2024,7/28/2024,5/20/2024,27,22,89,$7.00,91,77,2.17%

3. Data Transformation

In [ ]:

df['Unit_Price'] = df['Unit_Price'].str.replace('$', '', regex=False)

df['Unit_Price'] = df['Unit_Price'].astype(float)

4. Feature Engineering

In [ ]:
df['Inventory_Value'] = df['Stock_Quantity'] * df['Unit_Price']

df['Low_Stock'] = df['Stock_Quantity'] < df['Reorder_Level']

df.head()

,Product_Name,Catagory,Supplier_Name,Warehouse_Location,Status,Product_ID,Supplier_ID,Date_Received,Last_Order_Date,Expiration_Date,Stock_Quantity,Reorder_Level,Reorder_Quantity,Unit_Price,Sales_Volume,Inventory_Turnover_Rate,percentage,Inventory_Value,Low_Stock
0,Bell Pepper,Fruits & Vegetables,Eimbee,20 Pennsylvania Parkway,Discontinued,29-017-6255,43-348-2450,3/1/2024,1/6/2025,1/31/2025,46,64,17,4.6,96,55,1.96%,211.6,True
1,Vegetable Oil,Oils & Fats,Digitube,03643 Oakridge Lane,Backordered,79-569-8856,04-854-7165,4/1/2024,5/19/2024,6/11/2024,51,87,86,2.0,24,83,0.91%,102.0,True
2,Parmesan Cheese,Dairy,BlogXS,73 Graedel Street,Discontinued,28-146-2641,82-995-0739,4/1/2024,12/21/2024,4/8/2024,38,67,66,12.0,35,24,1.36%,456.0,True
3,Carrot,Fruits & Vegetables,Avaveo,44801 Myrtle Center,Discontinued,11-581-9869,22-867-3079,5/1/2024,12/12/2024,9/26/2024,51,60,98,1.5,44,95,1.36%,76.5,True
4,Garlic,Fruits & Vegetables,Katz,6195 Monterey Center,Discontinued,13-202-4809,24-281-7685,5/1/2024,7/28/2024,5/20/2024,27,22,89,7.0,91,77,2.17%,189.0,False

5. Data Validation

In [ ]:
df = df[df['Stock_Quantity'] >= 0]
df = df[df['Unit_Price'] >= 0]

df.describe()

,Stock_Quantity,Reorder_Level,Reorder_Quantity,Unit_Price,Sales_Volume,Inventory_Turnover_Rate,Inventory_Value
count,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000
mean,55.595551,51.245703,51.896866,5.862892,58.948433,50.165824,331.711587
std,26.310629,29.094069,29.531557,6.201248,23.002384,28.809489,414.044966
min,10.000000,1.000000,1.000000,0.200000,20.000000,1.000000,2.000000
25%,33.000000,26.000000,25.000000,2.500000,39.000000,25.000000,108.000000
50%,56.000000,53.000000,54.000000,4.200000,58.000000,50.000000,209.000000
75%,79.000000,77.000000,77.000000,7.000000,78.000000,75.000000,413.000000
max,100.000000,100.000000,100.000000,98.430000,100.000000,100.000000,5512.080000

6. Save ke Silver Layer

In [9]:
df.to_csv('silver_inventory.csv', index=False)
print('File berhasil disimpan sebagai silver_inventory.csv')

File berhasil disimpan sebagai silver_inventory.csv